package atomic

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Op) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "OpID":
			z.OpID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "OpID")
				return
			}
		case "Args":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Args")
				return
			}
			if cap(z.Args) >= int(zb0002) {
				z.Args = (z.Args)[:zb0002]
			} else {
				z.Args = make([]string, zb0002)
			}
			for za0001 := range z.Args {
				z.Args[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Args", za0001)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Op) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "OpID"
	err = en.Append(0x82, 0xa4, 0x4f, 0x70, 0x49, 0x44)
	if err != nil {
		return
	}
	err = en.WriteString(z.OpID)
	if err != nil {
		err = msgp.WrapError(err, "OpID")
		return
	}
	// write "Args"
	err = en.Append(0xa4, 0x41, 0x72, 0x67, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Args)))
	if err != nil {
		err = msgp.WrapError(err, "Args")
		return
	}
	for za0001 := range z.Args {
		err = en.WriteString(z.Args[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Args", za0001)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Op) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "OpID"
	o = append(o, 0x82, 0xa4, 0x4f, 0x70, 0x49, 0x44)
	o = msgp.AppendString(o, z.OpID)
	// string "Args"
	o = append(o, 0xa4, 0x41, 0x72, 0x67, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Args)))
	for za0001 := range z.Args {
		o = msgp.AppendString(o, z.Args[za0001])
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Op) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "OpID":
			z.OpID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "OpID")
				return
			}
		case "Args":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Args")
				return
			}
			if cap(z.Args) >= int(zb0002) {
				z.Args = (z.Args)[:zb0002]
			} else {
				z.Args = make([]string, zb0002)
			}
			for za0001 := range z.Args {
				z.Args[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Args", za0001)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Op) Msgsize() (s int) {
	s = 1 + 5 + msgp.StringPrefixSize + len(z.OpID) + 5 + msgp.ArrayHeaderSize
	for za0001 := range z.Args {
		s += msgp.StringPrefixSize + len(z.Args[za0001])
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *UndoLog) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "AID":
			z.AID, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "AID")
				return
			}
		case "Op":
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Op")
				return
			}
			for zb0002 > 0 {
				zb0002--
				field, err = dc.ReadMapKeyPtr()
				if err != nil {
					err = msgp.WrapError(err, "Op")
					return
				}
				switch msgp.UnsafeString(field) {
				case "OpID":
					z.Op.OpID, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "Op", "OpID")
						return
					}
				case "Args":
					var zb0003 uint32
					zb0003, err = dc.ReadArrayHeader()
					if err != nil {
						err = msgp.WrapError(err, "Op", "Args")
						return
					}
					if cap(z.Op.Args) >= int(zb0003) {
						z.Op.Args = (z.Op.Args)[:zb0003]
					} else {
						z.Op.Args = make([]string, zb0003)
					}
					for za0001 := range z.Op.Args {
						z.Op.Args[za0001], err = dc.ReadString()
						if err != nil {
							err = msgp.WrapError(err, "Op", "Args", za0001)
							return
						}
					}
				default:
					err = dc.Skip()
					if err != nil {
						err = msgp.WrapError(err, "Op")
						return
					}
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *UndoLog) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "AID"
	err = en.Append(0x82, 0xa3, 0x41, 0x49, 0x44)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.AID)
	if err != nil {
		err = msgp.WrapError(err, "AID")
		return
	}
	// write "Op"
	err = en.Append(0xa2, 0x4f, 0x70)
	if err != nil {
		return
	}
	// map header, size 2
	// write "OpID"
	err = en.Append(0x82, 0xa4, 0x4f, 0x70, 0x49, 0x44)
	if err != nil {
		return
	}
	err = en.WriteString(z.Op.OpID)
	if err != nil {
		err = msgp.WrapError(err, "Op", "OpID")
		return
	}
	// write "Args"
	err = en.Append(0xa4, 0x41, 0x72, 0x67, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Op.Args)))
	if err != nil {
		err = msgp.WrapError(err, "Op", "Args")
		return
	}
	for za0001 := range z.Op.Args {
		err = en.WriteString(z.Op.Args[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Op", "Args", za0001)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *UndoLog) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "AID"
	o = append(o, 0x82, 0xa3, 0x41, 0x49, 0x44)
	o = msgp.AppendUint64(o, z.AID)
	// string "Op"
	o = append(o, 0xa2, 0x4f, 0x70)
	// map header, size 2
	// string "OpID"
	o = append(o, 0x82, 0xa4, 0x4f, 0x70, 0x49, 0x44)
	o = msgp.AppendString(o, z.Op.OpID)
	// string "Args"
	o = append(o, 0xa4, 0x41, 0x72, 0x67, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Op.Args)))
	for za0001 := range z.Op.Args {
		o = msgp.AppendString(o, z.Op.Args[za0001])
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *UndoLog) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "AID":
			z.AID, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "AID")
				return
			}
		case "Op":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Op")
				return
			}
			for zb0002 > 0 {
				zb0002--
				field, bts, err = msgp.ReadMapKeyZC(bts)
				if err != nil {
					err = msgp.WrapError(err, "Op")
					return
				}
				switch msgp.UnsafeString(field) {
				case "OpID":
					z.Op.OpID, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Op", "OpID")
						return
					}
				case "Args":
					var zb0003 uint32
					zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Op", "Args")
						return
					}
					if cap(z.Op.Args) >= int(zb0003) {
						z.Op.Args = (z.Op.Args)[:zb0003]
					} else {
						z.Op.Args = make([]string, zb0003)
					}
					for za0001 := range z.Op.Args {
						z.Op.Args[za0001], bts, err = msgp.ReadStringBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "Op", "Args", za0001)
							return
						}
					}
				default:
					bts, err = msgp.Skip(bts)
					if err != nil {
						err = msgp.WrapError(err, "Op")
						return
					}
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *UndoLog) Msgsize() (s int) {
	s = 1 + 4 + msgp.Uint64Size + 3 + 1 + 5 + msgp.StringPrefixSize + len(z.Op.OpID) + 5 + msgp.ArrayHeaderSize
	for za0001 := range z.Op.Args {
		s += msgp.StringPrefixSize + len(z.Op.Args[za0001])
	}
	return
}
