// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: ringio/fspb/treefsservice.proto

package fspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDir      bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size       int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Hash       string                 `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	ModTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
}

func (x *SubInfo) Reset() {
	*x = SubInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ringio_fspb_treefsservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubInfo) ProtoMessage() {}

func (x *SubInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ringio_fspb_treefsservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubInfo.ProtoReflect.Descriptor instead.
func (*SubInfo) Descriptor() ([]byte, []int) {
	return file_ringio_fspb_treefsservice_proto_rawDescGZIP(), []int{0}
}

func (x *SubInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubInfo) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *SubInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SubInfo) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *SubInfo) GetModTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ModTime
	}
	return nil
}

func (x *SubInfo) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

type SpaceInfos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpaceName []string `protobuf:"bytes,1,rep,name=space_name,json=spaceName,proto3" json:"space_name,omitempty"`
}

func (x *SpaceInfos) Reset() {
	*x = SpaceInfos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ringio_fspb_treefsservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpaceInfos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceInfos) ProtoMessage() {}

func (x *SpaceInfos) ProtoReflect() protoreflect.Message {
	mi := &file_ringio_fspb_treefsservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceInfos.ProtoReflect.Descriptor instead.
func (*SpaceInfos) Descriptor() ([]byte, []int) {
	return file_ringio_fspb_treefsservice_proto_rawDescGZIP(), []int{1}
}

func (x *SpaceInfos) GetSpaceName() []string {
	if x != nil {
		return x.SpaceName
	}
	return nil
}

type Subs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubInfo []*SubInfo `protobuf:"bytes,1,rep,name=sub_info,json=subInfo,proto3" json:"sub_info,omitempty"`
}

func (x *Subs) Reset() {
	*x = Subs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ringio_fspb_treefsservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Subs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subs) ProtoMessage() {}

func (x *Subs) ProtoReflect() protoreflect.Message {
	mi := &file_ringio_fspb_treefsservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subs.ProtoReflect.Descriptor instead.
func (*Subs) Descriptor() ([]byte, []int) {
	return file_ringio_fspb_treefsservice_proto_rawDescGZIP(), []int{2}
}

func (x *Subs) GetSubInfo() []*SubInfo {
	if x != nil {
		return x.SubInfo
	}
	return nil
}

type SpaceStat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SpaceStat) Reset() {
	*x = SpaceStat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ringio_fspb_treefsservice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpaceStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceStat) ProtoMessage() {}

func (x *SpaceStat) ProtoReflect() protoreflect.Message {
	mi := &file_ringio_fspb_treefsservice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceStat.ProtoReflect.Descriptor instead.
func (*SpaceStat) Descriptor() ([]byte, []int) {
	return file_ringio_fspb_treefsservice_proto_rawDescGZIP(), []int{3}
}

func (x *SpaceStat) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SpaceStat) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetSpaceStatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Space *SpaceRequest `protobuf:"bytes,1,opt,name=space,proto3" json:"space,omitempty"`
	Key   string        `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetSpaceStatRequest) Reset() {
	*x = GetSpaceStatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ringio_fspb_treefsservice_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSpaceStatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpaceStatRequest) ProtoMessage() {}

func (x *GetSpaceStatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ringio_fspb_treefsservice_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpaceStatRequest.ProtoReflect.Descriptor instead.
func (*GetSpaceStatRequest) Descriptor() ([]byte, []int) {
	return file_ringio_fspb_treefsservice_proto_rawDescGZIP(), []int{4}
}

func (x *GetSpaceStatRequest) GetSpace() *SpaceRequest {
	if x != nil {
		return x.Space
	}
	return nil
}

func (x *GetSpaceStatRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetSpaceStatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stat *SpaceStat `protobuf:"bytes,1,opt,name=stat,proto3" json:"stat,omitempty"`
}

func (x *GetSpaceStatResponse) Reset() {
	*x = GetSpaceStatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ringio_fspb_treefsservice_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSpaceStatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpaceStatResponse) ProtoMessage() {}

func (x *GetSpaceStatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ringio_fspb_treefsservice_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpaceStatResponse.ProtoReflect.Descriptor instead.
func (*GetSpaceStatResponse) Descriptor() ([]byte, []int) {
	return file_ringio_fspb_treefsservice_proto_rawDescGZIP(), []int{5}
}

func (x *GetSpaceStatResponse) GetStat() *SpaceStat {
	if x != nil {
		return x.Stat
	}
	return nil
}

type SetSpaceStatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Space *SpaceRequest `protobuf:"bytes,1,opt,name=space,proto3" json:"space,omitempty"`
	Stat  *SpaceStat    `protobuf:"bytes,2,opt,name=stat,proto3" json:"stat,omitempty"`
}

func (x *SetSpaceStatRequest) Reset() {
	*x = SetSpaceStatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ringio_fspb_treefsservice_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetSpaceStatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSpaceStatRequest) ProtoMessage() {}

func (x *SetSpaceStatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ringio_fspb_treefsservice_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSpaceStatRequest.ProtoReflect.Descriptor instead.
func (*SetSpaceStatRequest) Descriptor() ([]byte, []int) {
	return file_ringio_fspb_treefsservice_proto_rawDescGZIP(), []int{6}
}

func (x *SetSpaceStatRequest) GetSpace() *SpaceRequest {
	if x != nil {
		return x.Space
	}
	return nil
}

func (x *SetSpaceStatRequest) GetStat() *SpaceStat {
	if x != nil {
		return x.Stat
	}
	return nil
}

type SpaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Space string `protobuf:"bytes,1,opt,name=space,proto3" json:"space,omitempty"`
}

func (x *SpaceRequest) Reset() {
	*x = SpaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ringio_fspb_treefsservice_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceRequest) ProtoMessage() {}

func (x *SpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ringio_fspb_treefsservice_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceRequest.ProtoReflect.Descriptor instead.
func (*SpaceRequest) Descriptor() ([]byte, []int) {
	return file_ringio_fspb_treefsservice_proto_rawDescGZIP(), []int{7}
}

func (x *SpaceRequest) GetSpace() string {
	if x != nil {
		return x.Space
	}
	return ""
}

type NewSpaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Space string `protobuf:"bytes,1,opt,name=space,proto3" json:"space,omitempty"`
	Cap   int64  `protobuf:"varint,2,opt,name=cap,proto3" json:"cap,omitempty"`
}

func (x *NewSpaceRequest) Reset() {
	*x = NewSpaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ringio_fspb_treefsservice_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewSpaceRequest) ProtoMessage() {}

func (x *NewSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ringio_fspb_treefsservice_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewSpaceRequest.ProtoReflect.Descriptor instead.
func (*NewSpaceRequest) Descriptor() ([]byte, []int) {
	return file_ringio_fspb_treefsservice_proto_rawDescGZIP(), []int{8}
}

func (x *NewSpaceRequest) GetSpace() string {
	if x != nil {
		return x.Space
	}
	return ""
}

func (x *NewSpaceRequest) GetCap() int64 {
	if x != nil {
		return x.Cap
	}
	return 0
}

type TreeFileSystemBasicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Space string `protobuf:"bytes,1,opt,name=space,proto3" json:"space,omitempty"`
	Base  string `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	Name  string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Hash  []byte `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *TreeFileSystemBasicRequest) Reset() {
	*x = TreeFileSystemBasicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ringio_fspb_treefsservice_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TreeFileSystemBasicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeFileSystemBasicRequest) ProtoMessage() {}

func (x *TreeFileSystemBasicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ringio_fspb_treefsservice_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeFileSystemBasicRequest.ProtoReflect.Descriptor instead.
func (*TreeFileSystemBasicRequest) Descriptor() ([]byte, []int) {
	return file_ringio_fspb_treefsservice_proto_rawDescGZIP(), []int{9}
}

func (x *TreeFileSystemBasicRequest) GetSpace() string {
	if x != nil {
		return x.Space
	}
	return ""
}

func (x *TreeFileSystemBasicRequest) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *TreeFileSystemBasicRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TreeFileSystemBasicRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type RenameDirRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src     *TreeFileSystemBasicRequest `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	NewName string                      `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
}

func (x *RenameDirRequest) Reset() {
	*x = RenameDirRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ringio_fspb_treefsservice_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenameDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameDirRequest) ProtoMessage() {}

func (x *RenameDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ringio_fspb_treefsservice_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameDirRequest.ProtoReflect.Descriptor instead.
func (*RenameDirRequest) Descriptor() ([]byte, []int) {
	return file_ringio_fspb_treefsservice_proto_rawDescGZIP(), []int{10}
}

func (x *RenameDirRequest) GetSrc() *TreeFileSystemBasicRequest {
	if x != nil {
		return x.Src
	}
	return nil
}

func (x *RenameDirRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type PutMetadataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src      *TreeFileSystemBasicRequest `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Metadata []byte                      `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *PutMetadataRequest) Reset() {
	*x = PutMetadataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ringio_fspb_treefsservice_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutMetadataRequest) ProtoMessage() {}

func (x *PutMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ringio_fspb_treefsservice_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutMetadataRequest.ProtoReflect.Descriptor instead.
func (*PutMetadataRequest) Descriptor() ([]byte, []int) {
	return file_ringio_fspb_treefsservice_proto_rawDescGZIP(), []int{11}
}

func (x *PutMetadataRequest) GetSrc() *TreeFileSystemBasicRequest {
	if x != nil {
		return x.Src
	}
	return nil
}

func (x *PutMetadataRequest) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type BytesData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BytesData) Reset() {
	*x = BytesData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ringio_fspb_treefsservice_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BytesData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytesData) ProtoMessage() {}

func (x *BytesData) ProtoReflect() protoreflect.Message {
	mi := &file_ringio_fspb_treefsservice_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytesData.ProtoReflect.Descriptor instead.
func (*BytesData) Descriptor() ([]byte, []int) {
	return file_ringio_fspb_treefsservice_proto_rawDescGZIP(), []int{12}
}

func (x *BytesData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_ringio_fspb_treefsservice_proto protoreflect.FileDescriptor

var file_ringio_fspb_treefsservice_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x72, 0x69, 0x6e, 0x67, 0x69, 0x6f, 0x2f, 0x66, 0x73, 0x70, 0x62, 0x2f, 0x74, 0x72,
	0x65, 0x65, 0x66, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x66, 0x73, 0x70, 0x62, 0x1a, 0x17, 0x72, 0x69, 0x6e, 0x67, 0x69, 0x6f, 0x2f,
	0x66, 0x73, 0x70, 0x62, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd0,
	0x01, 0x0a, 0x07, 0x53, 0x75, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x15,
	0x0a, 0x06, 0x69, 0x73, 0x5f, 0x64, 0x69, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x69, 0x73, 0x44, 0x69, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x35, 0x0a,
	0x08, 0x6d, 0x6f, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x6d, 0x6f, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x22, 0x2b, 0x0a, 0x0a, 0x53, 0x70, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x30,
	0x0a, 0x04, 0x53, 0x75, 0x62, 0x73, 0x12, 0x28, 0x0a, 0x08, 0x73, 0x75, 0x62, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x66, 0x73, 0x70, 0x62, 0x2e,
	0x53, 0x75, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x73, 0x75, 0x62, 0x49, 0x6e, 0x66, 0x6f,
	0x22, 0x33, 0x0a, 0x09, 0x53, 0x70, 0x61, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x51, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x70, 0x61, 0x63,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x05,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x66, 0x73,
	0x70, 0x62, 0x2e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x05, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x3b, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x53,
	0x70, 0x61, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x23, 0x0a, 0x04, 0x73, 0x74, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x66, 0x73, 0x70, 0x62, 0x2e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x52,
	0x04, 0x73, 0x74, 0x61, 0x74, 0x22, 0x64, 0x0a, 0x13, 0x53, 0x65, 0x74, 0x53, 0x70, 0x61, 0x63,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x05,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x66, 0x73,
	0x70, 0x62, 0x2e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x05, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x73, 0x74, 0x61, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66, 0x73, 0x70, 0x62, 0x2e, 0x53, 0x70, 0x61, 0x63,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x52, 0x04, 0x73, 0x74, 0x61, 0x74, 0x22, 0x24, 0x0a, 0x0c, 0x53,
	0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x22, 0x39, 0x0a, 0x0f, 0x4e, 0x65, 0x77, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x61,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x63, 0x61, 0x70, 0x22, 0x6e, 0x0a, 0x1a,
	0x54, 0x72, 0x65, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x42, 0x61,
	0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x62, 0x61, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x61, 0x0a, 0x10,
	0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x44, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x32, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x66, 0x73, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x65, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x03, 0x73, 0x72, 0x63, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x65, 0x77, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x77, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x64, 0x0a, 0x12, 0x50, 0x75, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x20, 0x2e, 0x66, 0x73, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x65, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x03, 0x73, 0x72, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x1f, 0x0a, 0x09, 0x42, 0x79, 0x74, 0x65, 0x73, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xe1, 0x05, 0x0a, 0x15, 0x54, 0x72, 0x65, 0x65, 0x46,
	0x69, 0x6c, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x30, 0x0a, 0x08, 0x4e, 0x65, 0x77, 0x53, 0x70, 0x61, 0x63, 0x65, 0x12, 0x15, 0x2e, 0x66,
	0x73, 0x70, 0x62, 0x2e, 0x4e, 0x65, 0x77, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x66, 0x73, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x22, 0x00, 0x12, 0x30, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x70, 0x61, 0x63,
	0x65, 0x12, 0x12, 0x2e, 0x66, 0x73, 0x70, 0x62, 0x2e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x66, 0x73, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x09, 0x41, 0x6c, 0x6c, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x10, 0x2e, 0x66, 0x73, 0x70, 0x62,
	0x2e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x00, 0x12, 0x47, 0x0a,
	0x0c, 0x47, 0x65, 0x74, 0x53, 0x70, 0x61, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x12, 0x19, 0x2e,
	0x66, 0x73, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x70, 0x61, 0x63, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x66, 0x73, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x70, 0x61, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x53, 0x70, 0x61,
	0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x12, 0x19, 0x2e, 0x66, 0x73, 0x70, 0x62, 0x2e, 0x53, 0x65,
	0x74, 0x53, 0x70, 0x61, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0b, 0x2e, 0x66, 0x73, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x00,
	0x12, 0x3a, 0x0a, 0x07, 0x4d, 0x61, 0x6b, 0x65, 0x44, 0x69, 0x72, 0x12, 0x20, 0x2e, 0x66, 0x73,
	0x70, 0x62, 0x2e, 0x54, 0x72, 0x65, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e,
	0x66, 0x73, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x09,
	0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x44, 0x69, 0x72, 0x12, 0x16, 0x2e, 0x66, 0x73, 0x70, 0x62,
	0x2e, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x44, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0b, 0x2e, 0x66, 0x73, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x00,
	0x12, 0x3c, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x69, 0x72, 0x12, 0x20, 0x2e,
	0x66, 0x73, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x65, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0b, 0x2e, 0x66, 0x73, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x00, 0x12, 0x3b,
	0x0a, 0x09, 0x47, 0x65, 0x74, 0x44, 0x69, 0x72, 0x53, 0x75, 0x62, 0x12, 0x20, 0x2e, 0x66, 0x73,
	0x70, 0x62, 0x2e, 0x54, 0x72, 0x65, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e,
	0x66, 0x73, 0x70, 0x62, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x0b, 0x47,
	0x65, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x20, 0x2e, 0x66, 0x73, 0x70,
	0x62, 0x2e, 0x54, 0x72, 0x65, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x66,
	0x73, 0x70, 0x62, 0x2e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x44, 0x61, 0x74, 0x61, 0x22, 0x00, 0x12,
	0x36, 0x0a, 0x0b, 0x50, 0x75, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18,
	0x2e, 0x66, 0x73, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x66, 0x73, 0x70, 0x62, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x20, 0x2e, 0x66, 0x73, 0x70, 0x62,
	0x2e, 0x54, 0x72, 0x65, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x42,
	0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x66, 0x73,
	0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x00, 0x42, 0x18, 0x5a, 0x16, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x62, 0x6f, 0x72, 0x61, 0x64, 0x2f, 0x72, 0x69, 0x6e, 0x67, 0x69, 0x6f, 0x2f,
	0x66, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ringio_fspb_treefsservice_proto_rawDescOnce sync.Once
	file_ringio_fspb_treefsservice_proto_rawDescData = file_ringio_fspb_treefsservice_proto_rawDesc
)

func file_ringio_fspb_treefsservice_proto_rawDescGZIP() []byte {
	file_ringio_fspb_treefsservice_proto_rawDescOnce.Do(func() {
		file_ringio_fspb_treefsservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_ringio_fspb_treefsservice_proto_rawDescData)
	})
	return file_ringio_fspb_treefsservice_proto_rawDescData
}

var file_ringio_fspb_treefsservice_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_ringio_fspb_treefsservice_proto_goTypes = []interface{}{
	(*SubInfo)(nil),                    // 0: fspb.SubInfo
	(*SpaceInfos)(nil),                 // 1: fspb.SpaceInfos
	(*Subs)(nil),                       // 2: fspb.Subs
	(*SpaceStat)(nil),                  // 3: fspb.SpaceStat
	(*GetSpaceStatRequest)(nil),        // 4: fspb.GetSpaceStatRequest
	(*GetSpaceStatResponse)(nil),       // 5: fspb.GetSpaceStatResponse
	(*SetSpaceStatRequest)(nil),        // 6: fspb.SetSpaceStatRequest
	(*SpaceRequest)(nil),               // 7: fspb.SpaceRequest
	(*NewSpaceRequest)(nil),            // 8: fspb.NewSpaceRequest
	(*TreeFileSystemBasicRequest)(nil), // 9: fspb.TreeFileSystemBasicRequest
	(*RenameDirRequest)(nil),           // 10: fspb.RenameDirRequest
	(*PutMetadataRequest)(nil),         // 11: fspb.PutMetadataRequest
	(*BytesData)(nil),                  // 12: fspb.BytesData
	(*timestamppb.Timestamp)(nil),      // 13: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 14: google.protobuf.Empty
	(*Error)(nil),                      // 15: fspb.Error
}
var file_ringio_fspb_treefsservice_proto_depIdxs = []int32{
	13, // 0: fspb.SubInfo.mod_time:type_name -> google.protobuf.Timestamp
	13, // 1: fspb.SubInfo.create_time:type_name -> google.protobuf.Timestamp
	0,  // 2: fspb.Subs.sub_info:type_name -> fspb.SubInfo
	7,  // 3: fspb.GetSpaceStatRequest.space:type_name -> fspb.SpaceRequest
	3,  // 4: fspb.GetSpaceStatResponse.stat:type_name -> fspb.SpaceStat
	7,  // 5: fspb.SetSpaceStatRequest.space:type_name -> fspb.SpaceRequest
	3,  // 6: fspb.SetSpaceStatRequest.stat:type_name -> fspb.SpaceStat
	9,  // 7: fspb.RenameDirRequest.src:type_name -> fspb.TreeFileSystemBasicRequest
	9,  // 8: fspb.PutMetadataRequest.src:type_name -> fspb.TreeFileSystemBasicRequest
	8,  // 9: fspb.TreeFileSystemService.NewSpace:input_type -> fspb.NewSpaceRequest
	7,  // 10: fspb.TreeFileSystemService.DeleteSpace:input_type -> fspb.SpaceRequest
	14, // 11: fspb.TreeFileSystemService.AllSpaces:input_type -> google.protobuf.Empty
	4,  // 12: fspb.TreeFileSystemService.GetSpaceStat:input_type -> fspb.GetSpaceStatRequest
	6,  // 13: fspb.TreeFileSystemService.SetSpaceStat:input_type -> fspb.SetSpaceStatRequest
	9,  // 14: fspb.TreeFileSystemService.MakeDir:input_type -> fspb.TreeFileSystemBasicRequest
	10, // 15: fspb.TreeFileSystemService.RenameDir:input_type -> fspb.RenameDirRequest
	9,  // 16: fspb.TreeFileSystemService.DeleteDir:input_type -> fspb.TreeFileSystemBasicRequest
	9,  // 17: fspb.TreeFileSystemService.GetDirSub:input_type -> fspb.TreeFileSystemBasicRequest
	9,  // 18: fspb.TreeFileSystemService.GetMetadata:input_type -> fspb.TreeFileSystemBasicRequest
	11, // 19: fspb.TreeFileSystemService.PutMetadata:input_type -> fspb.PutMetadataRequest
	9,  // 20: fspb.TreeFileSystemService.DeleteMetadata:input_type -> fspb.TreeFileSystemBasicRequest
	15, // 21: fspb.TreeFileSystemService.NewSpace:output_type -> fspb.Error
	15, // 22: fspb.TreeFileSystemService.DeleteSpace:output_type -> fspb.Error
	1,  // 23: fspb.TreeFileSystemService.AllSpaces:output_type -> fspb.SpaceInfos
	5,  // 24: fspb.TreeFileSystemService.GetSpaceStat:output_type -> fspb.GetSpaceStatResponse
	15, // 25: fspb.TreeFileSystemService.SetSpaceStat:output_type -> fspb.Error
	15, // 26: fspb.TreeFileSystemService.MakeDir:output_type -> fspb.Error
	15, // 27: fspb.TreeFileSystemService.RenameDir:output_type -> fspb.Error
	15, // 28: fspb.TreeFileSystemService.DeleteDir:output_type -> fspb.Error
	2,  // 29: fspb.TreeFileSystemService.GetDirSub:output_type -> fspb.Subs
	12, // 30: fspb.TreeFileSystemService.GetMetadata:output_type -> fspb.BytesData
	15, // 31: fspb.TreeFileSystemService.PutMetadata:output_type -> fspb.Error
	15, // 32: fspb.TreeFileSystemService.DeleteMetadata:output_type -> fspb.Error
	21, // [21:33] is the sub-list for method output_type
	9,  // [9:21] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_ringio_fspb_treefsservice_proto_init() }
func file_ringio_fspb_treefsservice_proto_init() {
	if File_ringio_fspb_treefsservice_proto != nil {
		return
	}
	file_ringio_fspb_error_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ringio_fspb_treefsservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ringio_fspb_treefsservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpaceInfos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ringio_fspb_treefsservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Subs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ringio_fspb_treefsservice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpaceStat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ringio_fspb_treefsservice_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSpaceStatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ringio_fspb_treefsservice_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSpaceStatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ringio_fspb_treefsservice_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetSpaceStatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ringio_fspb_treefsservice_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ringio_fspb_treefsservice_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewSpaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ringio_fspb_treefsservice_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TreeFileSystemBasicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ringio_fspb_treefsservice_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenameDirRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ringio_fspb_treefsservice_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutMetadataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ringio_fspb_treefsservice_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BytesData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ringio_fspb_treefsservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ringio_fspb_treefsservice_proto_goTypes,
		DependencyIndexes: file_ringio_fspb_treefsservice_proto_depIdxs,
		MessageInfos:      file_ringio_fspb_treefsservice_proto_msgTypes,
	}.Build()
	File_ringio_fspb_treefsservice_proto = out.File
	file_ringio_fspb_treefsservice_proto_rawDesc = nil
	file_ringio_fspb_treefsservice_proto_goTypes = nil
	file_ringio_fspb_treefsservice_proto_depIdxs = nil
}
