# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "dev0" ]
  pull_request:
    branches: [ "dev0" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install Protoc
      uses: arduino/setup-protoc@v2
        
    - name: Install Protoc-gen-go
      run: go install github.com/golang/protobuf/protoc-gen-go/
      
    - name: Install Protoc-gen-go-grpc
      run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

    - name: generate protobuf code
      run: sh genprotobuf.sh
    
    - name: Build
      run: CGO_ENABLED=0 go build -o cloud_board

    - name: SCP Files0
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_SERVER_0 }}
        username: ${{ secrets.REMOTE_SERVER_USER }} 
        port: ${{ secrets.REMOTE_SERVER_PORT }}
        key: ${{ secrets.SERVER_SSH_KEY }} 
        source: 'cloud_board'
        target: ${{ secrets.REMOTE_SERVER_PATH }}

    - name: SCP Files1
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_SERVER_1 }}
        username: ${{ secrets.REMOTE_SERVER_USER }} 
        port: ${{ secrets.REMOTE_SERVER_PORT }}
        key: ${{ secrets.SERVER_SSH_KEY }} 
        source: 'cloud_board' 
        target: ${{ secrets.REMOTE_SERVER_PATH }}

    - name: SCP Files2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_SERVER_2 }}
        username: ${{ secrets.REMOTE_SERVER_USER }} 
        port: ${{ secrets.REMOTE_SERVER_PORT }}
        key: ${{ secrets.SERVER_SSH_KEY }} 
        source: 'cloud_board'
        target: ${{ secrets.REMOTE_SERVER_PATH }}
